### ISSUE TITLE
Custom Spawns module broken

### ISSUE THREAD

**Issue by Turbine1991** [GhoulofGSG9/ShineExtraPlugins#1]
Using custom spawns always results in the error thrown: "Couldn't find a valid spawn set-up file for ns2_summit, disabling the plug-in for now"

The problem persists even when Shine Ex has generated a new spawn file, using the default values.

**Comment by GhoulofGSG9** [comment]
Fixed with https://github.com/GhoulofGSG9/ShineExtraPlugins/commit/12d75c56f0c3814871587d61f378340f37ee0fcd
