### ISSUE TITLE
Scroll to top of list after list no longer needs to be scrollable.

### ISSUE THREAD

**Issue by akrigline** [GhoulofGSG9/ShineExtraPlugins#15]
With regards to Captains.

Sometimes players "don't show up" on the pick list at the end of the picking process. They've moved around in the RR so aren't AFK. My theory is that the captain has scrolled down in the list before the list no longer needs to be scrollable. Then once the list drops below the scroll threshold, it doesn't scroll back to the top. So there's one or two guys at the top of the list that the captain can't get to.

Perhaps ensure that the list scrolls to top whenever the scrolling functionality goes away?

**Comment by GhoulofGSG9** [comment]
Actually this is a valid idea what could be bugging out there. Thanks for the input

**Comment by Person8880** [comment]
This behaviour should be fixed in the next Shine update. It's my fault, the code for the list/panel objects was not accounting for when the maximum height shrunk, only increasing.

**Comment by GhoulofGSG9** [comment]
Thanks @Person8880
