### ISSUE TITLE
Captain is AFK and gets voted in

### ISSUE THREAD

**Issue by Rusty01** [GhoulofGSG9/ShineExtraPlugins#17]
We need a way for the readyroom people to vote for a new captain.
Initially people vote and the system picks two captains.   What if it also picked a third " back-up " captain using the votes that were in.

If a captain does not vote within two minutes,  they are replaced.   Have it on a LARGE timer.

*\* the only fix at the moment is to change maps if admin/mod is not present - or switch servers **

**Comment by GhoulofGSG9** [comment]
Should have been fixed with Issue #10
