### ISSUE TITLE
* The ability for late joiners to ongoing games to automatically be assigned to a team 

### ISSUE THREAD

**Issue by Rusty01** [GhoulofGSG9/ShineExtraPlugins#21]
- The ability for late joiners to ongoing games to automatically be assigned to a team without needing to be chosen by a Captain (Not a big deal but it'd be nice)

We notice a lot of captains don't add people after a game starts.  this means long wait times in the readyroom.   Having the system automatically add players to teams would be great.

**Comment by GhoulofGSG9** [comment]
New players should get auto-assigned to a team once the round has started already
