### ISSUE TITLE
AFK Captains being picked.    Still a problem.

### ISSUE THREAD

**Issue by Rusty01** [GhoulofGSG9/ShineExtraPlugins#22]
Is it possible for the mod to detect AFKs and make them unpickable, or even have the mod that shows {AFK} beside someones username?

**Comment by GhoulofGSG9** [comment]
It filters out afk winners at the end of a vote. By this no afk player will ever become captain.
It would be possible to hide the vote for afk player but that probably is a ways to aggressive solution for the problem.

The current solution solves the problem with only a few extra steps needed and no need for sending additional details to the clients.

If AFK players are a issue try to lower the AFKLimit value to 0.5 (30 secs) or 0.25 (15 secs)
