### ISSUE TITLE
IgnoreShineForce setting in enforceteamsizes breaks team shuffling

### ISSUE THREAD

**Issue by Person8880** [GhoulofGSG9/ShineExtraPlugins#26]
I've been seeing error reports recently around unbalanced teams after a team sort. Wondering what could have changed, I saw that you've added an option for ignoring the force parameter Shine passes through.

Due to the nature of the team swapping (i.e. it moves everyone that should be on marines to marines, then everyone that should be on aliens to aliens), there'll potentially be a point where the marine team size exceeds the maximum at the halfway point. Because your plugin denies team joining, this leaves teams in an unbalanced state and breaks the shuffling.

With that being said, you're obviously going to need to have some way to know that a shuffle's taken place and to act on it after. Let me know what kind of event would be useful (post EvenlySpreadTeams perhaps?) and I can add it so you don't have to hack around the force flag.

**Comment by GhoulofGSG9** [comment]
I totally forgot that i added this option. I only added it back then because it was requested and i didn't had time to solve the "problem" properly.

Best for me actually would be an event previous to `EvenlySpreadTeams` with would allow me to modify the passed `TeamMembers` table to my needs.
