### ISSUE TITLE
problems with shuffle in shine when using this plugin

### ISSUE THREAD

**Issue by myrljus** [GhoulofGSG9/ShineExtraPlugins#27]
On Woozas HamsterWheel we have a setup with 32 players and 10 specs, and shuffling sometimes makes the teams overrun the team size limit. Sometimes we end up with 19 vs 16 and variations there of. This happens after a voted shuffle or sh_enablerandom

**Comment by GhoulofGSG9** [comment]
https://github.com/GhoulofGSG9/Shine-Epsilon/commit/9e8deae7fb073ba14c1c4f8f7d11bc1fa1906f01 lowers the risk of that this happens and if it happens the plug-in will report all details i need to look further into the situation.
