### ISSUE TITLE
Broke in latest update?

### ISSUE THREAD

**Issue by alextd** [GhoulofGSG9/ShineExtraPlugins#28]
Can't buy guns or evolve with latest update just released - (is this the mod that servers are currently using?)

**Comment by alextd** [comment]
I guess it's adressed here: https://github.com/GhoulofGSG9/Shine-Epsilon/commit/9cda4496ffd888129c8cbbb4b4740fc1510856cc

**Comment by GhoulofGSG9** [comment]
Yeah build 278 changed the script load order. I tried to band-aid fix this by moving the hook setup to a later point. But turns out the Think event is called too late. Will fix this issue tomorrow.
