### ISSUE TITLE
Change enforceteamsizes to use the PreShuffleOptimiseTeams event

### ISSUE THREAD

**Issue by Person8880** [GhoulofGSG9/ShineExtraPlugins#29]
The last update to Shine added the `PreShuffleOptimiseTeams` event. You should use this to make sure that you make your changes to team sizes before the teams are balanced. Otherwise, the carefully optimised teams end up disrupted and the shuffle ineffective.

**Comment by GhoulofGSG9** [comment]
Do i still have to move removed players to the Ready Room or is that already done by the Vote Random plugin?

**Comment by Person8880** [comment]
You will have to move them, as this is just the set of team members that are about to be re-distributed around.

**Comment by GhoulofGSG9** [comment]
Okay thanks for the info i updated enforceteamsizes
