### ISSUE TITLE
Potential Custom Spawns/Cross Spawns issue

### ISSUE THREAD

**Issue by Turbine1991** [GhoulofGSG9/ShineExtraPlugins#3]
This may or may not be caused by custom spawns, but it's only appeared since enabling shine extras + custom spawns.

Sometimes maps which don't even have customs spawns enabled, spawns the two teams right next to each other. For example, in Summit Aliens started in Sub and Marines in Datacore. It may also be happening occasionally for maps with custom spawns.

This issue is resolved if there's no possible way the module is interfering with maps when custom spawns are disabled for the particular map.

**Comment by GhoulofGSG9** [comment]
Okay, none of the plug-in's methods get called after the plug-in got disabled on a map via the con-fig. 

I checked that by adding debug prints to each method.

Furthermore "close spawns" are common for most vanilla maps. The reason this plug-in came into life originally.

Here the "spawn-dump" of summit:

``` json
[{
      "enemyspawns":["data core","flight control","atrium","sub access"],
      "name":"data core",
      "team":"both"
    },{
      "enemyspawns":["data core","flight control","atrium","sub access"],
      "name":"flight control",
      "team":"both"
    },{
      "enemyspawns":["data core","flight control","atrium","sub access"],
      "name":"atrium",
      "team":"both"
    },{
      "enemyspawns":[],
      "name":"crossroads",
      "team":"none"
    },{
      "enemyspawns":["data core","flight control","atrium","sub access"],
      "name":"sub access",
      "team":"both"
    }]
```

I don't unload the plug-in (like i do on a map config parsing issue) if it gets disabled for the given current map, so you are able to use `sh_dumpspawns`.

**Comment by Turbine1991** [comment]
Thank you, I appreciate this very much. It really does just enforce how beneficial this mod is to all servers.

If only the CDT took this kind of initiative more seriously.
