### ISSUE TITLE
NoRookie plugin - request new variable - to allow rookies to command "seed games" at low pop.

### ISSUE THREAD

**Issue by Rusty01** [GhoulofGSG9/ShineExtraPlugins#34]
Can we please have a variable added.
I would like to be able to specify that rookies can command - until there is 12 players on the server.
This way rookies can create seed games while they wait for veterans.

This variable is only needed for people to command.   It shouldn't take into account number of bots,  nor should it boot them out if more join after the game has started.   It's strictly added as a seed game feature. # #

**Comment by Wooza42** [comment]
Add following value in norookie.json:
"MinPlayer": 12,
Will activate the plugin only when there is 12 or more people on the server.
More Infos can be found here: https://github.com/GhoulofGSG9/Shine-Epsilon/wiki/NoRookies

**Comment by Rusty01** [comment]
ty Wooza,  but what I am looking for is two min req.   one for playing, one for commanding.
