### ISSUE TITLE
[PreGamePlus] Resetting round mid-game

### ISSUE THREAD

**Issue by Turbine1991** [GhoulofGSG9/ShineExtraPlugins#4]
After the round has begin, this mod has now started to end the game pre-maturely. I'm uncertain of how long after the round begin, I just know it's happened quite a few times.

This is still happened right up to the latest release (3rd push from the 18th of April).

[Edit]
I've been told the multiple server crashes might have been caused by the mod updating. So the only issue is the premature round resetting.

**Comment by GhoulofGSG9** [comment]
Thanks for reporting, indeed my unit test wasn't covering one case where this "round restart"- issue was still happening.

That one should be solved with https://github.com/GhoulofGSG9/ShineExtraPlugins/commit/1809049387243f754790dda0518743350c95b967

I have no clue how this mod should crash any server, it is not using anything that would be able to break out of the lua vm.

The crashes might be related to something else. Could you get the crash dumps and logs from those crashs?

**Comment by Turbine1991** [comment]
The crashes apparently aren't unusual for some shine mods updating. Might be a workshop/ns2 thing.

We will try the latest ns2 plus in a few days after being of being stable.

**Comment by Turbine1991** [comment]
I just tried the latest PreGamePlus yesterday, and it wouldn't even let me evolve. The old version however works.
