### ISSUE TITLE
NoRookies: CheckCommLogin not invoked

### ISSUE THREAD

**Issue by hdcstfg** [GhoulofGSG9/ShineExtraPlugins#43]
Hi Ghoul,
i would like to ask for your support.

I've tried to set up that rookie players are allowed to play but no one should command below 1000 hours.

Since the following settings ...
```
"BlockCC": true,
"BlockTeams": false,
"MinComPlaytime": 1000,
"MinPlaytime": 0,
"MinPlayer": 0,
"MinPlayerCom": 0,
```
... did not denies them getting into CC, i've tried to figure it out what is happening and found that  _Plugin:CheckValues_ wont be invoked unless _BlockTeams_ is set to true.

On _"BlockTeams": true_ the check is done right,
`[01:10:06]NoRookie Debug: Playtime of 4363017 = 9771 secs, Passed Check 1? true`
but function _Plugin:CheckCommLogin_ still wont be invoked and everyone is allowed command.

Could You please check the issue and provide me hints in case its config-related, 
or -in case its broken or its a bug- then fix this?

Thanks in advance!

ps.
Could You please also review that _BlockTeams_ causing _Server.DisableQuickPlay()_, however the setting _MinPlaytime=0_ is overriding its effect.

**Comment by GhoulofGSG9** [comment]
Thanks for the detailed issue report. I fixed the issue and released an update to workshop.
