### ISSUE TITLE
NSL Fetching does not work with linux

### ISSUE THREAD

**Issue by snooops** [GhoulofGSG9/ShineExtraPlugins#44]
Hi,
as Person8880 has figured out this is related to some redirect handling which isn't working proper under linux. Can you pls check it?

https://github.com/Person8880/Shine/issues/814

**Comment by GhoulofGSG9** [comment]
Hey,

sorry for the late response. I'll look into it. My fear is that it may come down to the linux curl module used by spark rejecting the ensl.org let's encrypt TLS cypher. Did run into that issue previously.

**Comment by snooops** [comment]
Hi Ghoul,

as you mentioned in discrod, i didn't execute the binary from this directory, that went to this error. 
I'm now running the server command directly from the x64 folder and it's working ;) Thanks a lot

**Comment by GhoulofGSG9** [comment]
Closing this as it seem to be related to that the given Linux server in question wasn't started directly inside the x64 directory causing curl to run without proper CA certs causing the TLS handshake to fail.

**Comment by GhoulofGSG9** [comment]
@snooops Looks like you were faster ;)
