### ISSUE TITLE
Hive team restrictions plugin causes imbalanced teams after shuffle

### ISSUE THREAD

**Issue by Person8880** [GhoulofGSG9/ShineExtraPlugins#46]
The [`PreShuffleOptimiseTeams` method in the `hiveteamrestrictions` plugin](https://github.com/GhoulofGSG9/Shine-Epsilon/blob/master/lua/shine/extensions/hiveteamrestriction/server.lua#L350) refers to the global `Gamerules` class instead of the current gamerules instance, which results in the team movement failing. This leaves players that are supposed to be restricted still on the playing team, but no longer visible to the shuffle pass, making teams uneven.

The error is suppressed by the `pcall`, hence it going unnoticed for a long time.

**Comment by GhoulofGSG9** [comment]
Thanks for reporting this issue.

Sorry it took so long to fix but I haven't been able to really work on private projects for the last months due to not having my own dev environment available. 

I wish you happy holidays and all the best for 2021.

**Comment by Person8880** [comment]
That's fine, there was no rush. Best wishes to you over the holidays and new year too. 🙂
