### ISSUE TITLE
Spectator Queue Plugin - needs an update.

### ISSUE THREAD

**Issue by Rusty01** [GhoulofGSG9/ShineExtraPlugins#47]
Hi, hope you had good holidays :)
So there's a problem ( non functional ) with the ready room queue plugin.

When you are in the spectator queue, you can normally press F4 to see your position. However what you see now is. "

NOTIFY_PREFIX QUEUE POSITION
NOTIFY_PREFIX QUEUE_WAITITME

Thanks.
![20201229225441_1](https://user-images.githubusercontent.com/12983350/103328993-e66d4480-4a28-11eb-9825-dd4e90c61b55.jpg)

**Comment by GhoulofGSG9** [comment]
I forgot to include the localization files with the latest mod update. Should be resolved now.
