### ISSUE TITLE
Killstreak bugs

### ISSUE THREAD

**Issue by Hitman4** [GhoulofGSG9/ShineExtraPlugins#49]
sh_disablesounds and sh_setsoundvolume not work for me and sounds too loud i tryed to set it to 10-20 but nothing changed in the config

**Comment by GhoulofGSG9** [comment]
The commands are `sh_sounds` and `sh_soundvolume`. Did you mean those? They worked just fine for me in a quick test. 

Are there any errors in the server / client log?

**Comment by GhoulofGSG9** [comment]
Oh I see. I need to update the startup message.

**Comment by Hitman4** [comment]
nice no i don't saw an error but it not changed the volume or turn it off :/

**Comment by GhoulofGSG9** [comment]
Fixed the startup message.
